In [1]:
import pandas as pd

df = pd.read_csv('streams_sucios.csv')

print("Archivo cargado exitosamente")
print(f"Dimensiones iniciales: {df.shape[0]} filas × {df.shape[1]} columnas")
display(df.head())

Archivo cargado exitosamente
Dimensiones iniciales: 20300 filas × 5 columnas

,ID_Transmision,Canal,Categoria,Espectadores_Pico,Horas_Transmitidas
0,5681,Streamer_4681,Esports,10624.0,5.6
1,12311,Streamer_11311,Arte,24621.0,11.6
2,6210,Streamer_5210,Musica,40218.0,6.2
3,4142,Streamer_3142,Musica,7496.0,6.9
4,20972,Streamer_19972,Esports,46044.0,6.9

In [3]:
# Contar valores nulos por columna
print("📋 Valores nulos por columna:")
display(df.isnull().sum())

# Contar filas duplicadas exactas
duplicados = df.duplicated().sum()
print(f"\n🔄 Filas duplicadas exactas: {duplicados}")

# Total de filas antes de limpiar
print(f"\n📈 Total de filas iniciales: {len(df)}")

📋 Valores nulos por columna:

ID_Transmision          0
Canal                 150
Categoria             400
Espectadores_Pico     250
Horas_Transmitidas      0
dtype: int64

🔄 Filas duplicadas exactas: 275

📈 Total de filas iniciales: 20300

In [4]:
# Eliminar filas donde la columna 'Canal' es nula
df = df.dropna(subset=['Canal'])

print(f"Filas sin 'Canal' eliminadas. Filas restantes: {len(df)}")

Filas sin 'Canal' eliminadas. Filas restantes: 20150

In [5]:
# Rellenar nulos en 'Categoria' con texto por defecto
df['Categoria'] = df['Categoria'].fillna('Sin Clasificar')

print("Columna 'Categoria' completada con 'Sin Clasificar'")

Columna 'Categoria' completada con 'Sin Clasificar'

In [7]:
# Rellenar nulos en 'Espectadores_Pico' con 0 (valor numérico)
df['Espectadores_Pico'] = df['Espectadores_Pico'].fillna(0)

print("Columna 'Espectadores_Pico' completada con 0")

Columna 'Espectadores_Pico' completada con 0

In [8]:
# Verificar que no queden nulos
print("Valores nulos restantes:")
print(df.isnull().sum())

# Verificar tamaño final
print(f"\n Tamaño final del DataFrame: {df.shape[0]} filas × {df.shape[1]} columnas")

# Mostrar resumen rápido
print("\n Primeras 5 filas del dataset limpio:")
display(df.head())

Valores nulos restantes:
ID_Transmision        0
Canal                 0
Categoria             0
Espectadores_Pico     0
Horas_Transmitidas    0
dtype: int64

 Tamaño final del DataFrame: 20150 filas × 5 columnas

 Primeras 5 filas del dataset limpio:

,ID_Transmision,Canal,Categoria,Espectadores_Pico,Horas_Transmitidas
0,5681,Streamer_4681,Esports,10624.0,5.6
1,12311,Streamer_11311,Arte,24621.0,11.6
2,6210,Streamer_5210,Musica,40218.0,6.2
3,4142,Streamer_3142,Musica,7496.0,6.9
4,20972,Streamer_19972,Esports,46044.0,6.9

In [9]:
# 1. Filtrar solo categoría 'Gaming'
df_gaming = df[df['Categoria'] == 'Gaming']

# 2. Encontrar el récord máximo de espectadores en Gaming
max_espectadores = df_gaming['Espectadores_Pico'].max()

# 3. Identificar al streamer que logró ese récord
streamer_record = df_gaming.loc[df_gaming['Espectadores_Pico'].idxmax(), 'Canal']

# 4. Armar el informe gerencial con print() redactado
print("REPORTE GERENCIAL - RECOMENDACIÓN DE PATROCINIO")
print("=" * 60)
print(f"Categoría analizada: Gaming")
print(f"Streamers en esta categoría: {len(df_gaming)}")
print(f"Récord de espectadores: {max_espectadores:,.0f}")
print(f"Streamer destacado: {streamer_record}")
print("-" * 60)
print(f"RECOMENDACIÓN: Se sugiere priorizar el patrocinio oficial")
print(f"   de '{streamer_record}', quien alcanzó el máximo histórico")
print(f"   de audiencia en la categoría Gaming con {max_espectadores:,.0f} espectadores.")
print("=" * 60)

REPORTE GERENCIAL - RECOMENDACIÓN DE PATROCINIO
============================================================
Categoría analizada: Gaming
Streamers en esta categoría: 3896
Récord de espectadores: 49,997
Streamer destacado: Streamer_10015
------------------------------------------------------------
RECOMENDACIÓN: Se sugiere priorizar el patrocinio oficial
   de 'Streamer_10015', quien alcanzó el máximo histórico
   de audiencia en la categoría Gaming con 49,997 espectadores.
============================================================